### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by repoman728** [BITINTERN/Crypto-Wallet-Finder-Software-#3]
Solved.

**Comment by BITINTERN** [comment]
I am really sorry for the inconvenience....plz ping me I will your issue.

**Comment by BITINTERN** [comment]
I am really sorry for the inconvenience....plz ping me I will your issue. 
And don't use VPN.

**Comment by repoman728** [comment]
> I am really sorry for the inconvenience....plz ping me I will solve your issue. 

Where ,in telegram?

**Comment by BITINTERN** [comment]
Don't you buy from  bit intern.

**Comment by repoman728** [comment]
> Don't you buy from  bit intern?

How I buy from you

**Comment by repoman728** [comment]
But in your page says for password contact  telegram  team

**Comment by repoman728** [comment]
But in your page says for password contact  telegram  team and it is open and got  me to  WENZY GEEK  , if that guy it not your thats mean   youweb page Been 
Hacked and I lost money.
WENZYGEEK IS SCAM , AVOID !!!!!!!

**Comment by repoman728** [comment]
It is not solved¡!!!!!

**Comment by repoman728** [comment]
I have to use vpn cause telegram is blocked
