### ISSUE TITLE
I waiting on the key

### ISSUE THREAD

**Issue by Pinki2812** [BITINTERN/Crypto-Wallet-Finder-Software-#7]
I was bought the Tool since 1 h ,ago. But the guy Don t send it to me. Can you help me please ? Unfortunately, I am also to blame because it took me a long time to send. Just thought that maybe I could let you know here
 :)

**Comment by sucideface** [comment]
I don’t understand what do you want

**Comment by Pinki2812** [comment]
I thought I could let you know here so that the license key can be sent to me. Because I have the Telegram names from here. Unfortunately, I'm also new here and didn't know how to let you know.  

I'm sorry if it was wrong.

**Comment by sucideface** [comment]
What key lol

**Comment by sucideface** [comment]
Wrong address and how did you get my email address?

**Comment by Pinki2812** [comment]
From the crypto finder tool? Oh, sorry. I just commented under the tool.
